/**
 * SITE CONFIG — edit this file by hand.
 * Nothing else in the site needs to change when you add pages, rename
 * files, or update the Hall of Fame.
 */
const SITE_CONFIG = {

  // The Archives listing is generated by generate-archive.sh, not read
  // here — that script has its own EXCLUDED_FILES array at the top, so
  // that's the one place to edit which files get left out.

  // Hand-picked links for the Hall of Fame section. "url" can point
  // anywhere, not just at files in this repo.
  hallOfFame: [
    { title: "Placeholder entry one", url: "https://www.google.com" },
    { title: "Placeholder entry two", url: "https://www.google.com" },
    { title: "Placeholder entry three", url: "https://www.google.com" }
  ]
};
