#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")"

ARCHIVE_FILE="archive.html"
START_MARKER="<!-- ARCHIVE:START - generated by generate-archive.sh, do not edit by hand -->"
END_MARKER="<!-- ARCHIVE:END -->"

EXCLUDED_FILES=(
  "index.html"
  "archive.html"
)

is_excluded() {
  local relpath="$1" base entry
  base="$(basename "$relpath")"
  for entry in "${EXCLUDED_FILES[@]}"; do
    if [[ "$entry" == */* ]]; then
      [[ "$entry" == "$relpath" ]] && return 0
    else
      [[ "$entry" == "$base" ]] && return 0
    fi
  done
  return 1
}

slugify() {
  local s="${1,,}"
  s="${s//\//-}"
  s="$(sed -E 's/[^a-z0-9-]+/-/g; s/-+/-/g; s/^-//; s/-$//' <<< "$s")"
  echo "dir-${s:-root}"
}

label_for() {
  local base
  base="$(basename "$1" .html)"
  base="${base//[-_]/ }"
  echo "$(tr '[:lower:]' '[:lower:]' <<< "${base:0:1}")${base:1}"
}

mapfile -t files < <(find . -type f -name "*.html" -printf '%P\n' | sort)

declare -A FILES_BY_DIR
declare -a DIR_ORDER

for f in "${files[@]}"; do
  is_excluded "$f" && continue
  dir="$(dirname "$f")"
  [[ "$dir" == "." ]] && dir=""
  li="    <li><a href=\"$f\">$(label_for "$f")</a></li>"
  if [[ -z "${FILES_BY_DIR[$dir]+x}" ]]; then
    FILES_BY_DIR[$dir]="$li"
    DIR_ORDER+=("$dir")
  else
    FILES_BY_DIR[$dir]+=$'\n'"$li"
  fi
done

BODY_FILE="$(mktemp)"
{
  for dir in "${DIR_ORDER[@]}"; do
    echo "  <div class=\"archive-group\" id=\"$(slugify "${dir:-root}")\">"
    echo "    <h3>${dir:-(root)}</h3>"
    echo "    <ul class=\"archive-list\">"
    echo "${FILES_BY_DIR[$dir]}"
    echo "    </ul>"
    echo "  </div>"
  done
} > "$BODY_FILE"

OUT_FILE="$(mktemp)"
awk -v start="$START_MARKER" -v end="$END_MARKER" -v bodyfile="$BODY_FILE" '
  index($0, start) { print; fflush(); while ((getline line < bodyfile) > 0) print line; skipping=1; next }
  index($0, end)   { skipping=0 }
  !skipping        { print }
' "$ARCHIVE_FILE" > "$OUT_FILE" && mv "$OUT_FILE" "$ARCHIVE_FILE"
rm -f "$BODY_FILE"

link_count=$(grep -c '<li><a' "$ARCHIVE_FILE" || true)
echo "Done — wrote ${link_count} file(s) across ${#DIR_ORDER[@]} folder(s) into $ARCHIVE_FILE."
